---
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin      # thiếu gói này thì không có lệnh `docker compose`
docker_users:
  - "{{ app_user }}"
