[dataops_nodes]
vm1 ansible_host=192.168.64.2 ansible_user=dataops
vm2 ansible_host=192.168.64.3 ansible_user=dataops
vm3 ansible_host=192.168.64.4 ansible_user=dataops

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3