services:
  node-exporter:
    image: prom/node-exporter:v1.11.1
    container_name: node_exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      # Nơi các cron job ghi metric của mình ra file .prom
      - /var/lib/node_exporter/textfile:/textfile:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.textfile.directory=/textfile'
    ports:
      - "9100:9100"

networks:
  default:
    driver: bridge
